@startuml
skinparam dpi 150

'Player抽象クラス
abstract class Player {
	+void Attack(Weapons weapon)
}

'剣士クラス
class Swordman {
  +void Attack(Weapons weapon)
}
'魔法使いクラス
class Wizard {
  +void Attack(Weapons weapon)
}

'武器インターフェース
abstract class Weapons {
	+string name
	+int power
}
'剣クラス
class Sword {
  +string name
  +int power
}
'魔法の杖クラス
class MagicWand {
  +string name
  +int power
}


' クラス間の関係
Player <|-- Swordman
Player <|-- Wizard
Player -|> Weapons
Weapons <|-- Sword
Weapons <|-- MagicWand
@enduml